name: immutable_state
description: "🎯 A lightweight framework for stateless UI in Dart and Flutter, and an alternative to Redux."
version: 1.1.0
author: Tobe Osakwe <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/immutable_state
environment:
  sdk: ">=2.0.0 <3.0.0"
dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
