name: example
description: A new Flutter project.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_immutable_state:
    path: ../flutter_immutable_state
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true